# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'KeyVaultPasswords'

steps:
- bash: echo $(mongo-db-password)

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install typescript -g
    tsc
  displayName: 'npm install and build'

- script: |
    npm run test
  displayName: 'run unit tests'

- script: |
    echo 'Build informations: $(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)'
  displayName: 'Build informations'

- task: CopyFiles@2
  displayName:
  inputs:
    contents: 'coverage/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: CoverageReport

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Pay-As-You-Go (478a713b-334d-4d58-b9f4-34839c5a7530)'
    KeyVaultName: 'AZPFKeyVaultLearning'
    SecretsFilter: '*'

- task: PowerShell@2
  inputs:
    filePath: './powershell-poc.ps1'